resources:
  - namespace.yaml
  - config_map.yaml
  - https://raw.githubusercontent.com/argoproj/argo-workflows/v3.2.6/manifests/quick-start-minimal.yaml

images:
  - name: quay.io/argoproj/argocli
    newTag: v3.2.6

namespace: argo
