apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: k8s-example-
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  entrypoint: k8s-get-ns

  templates:
    - name: k8s-get-ns
      resource:
        action: get
        manifest: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: default
